import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/keybinds.toml"]
live_config_reload = true

[env]
TERM = "alacritty"

[shell]
args = ["--login"]
program = "/opt/homebrew/bin/fish"

[font]
size = 12.0

[font.normal]
family = "MonoLisa Nerd Font"
style = "Medium Regular"

[font.bold]
family = "MonoLisa Nerd Font"
style = "Bold Regular"

[font.italic]
family = "MonoLisa Nerd Font"
style = "Medium Italic"

[font.bold_italic]
family = "MonoLisa Nerd Font"
style = "Bold Italic"

[font.offset]
x = 1
y = 14

[font.glyph_offset]
x = 0
y = 7

[cursor]
unfocused_hollow = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "buttonless"
startup_mode = "Windowed"
dynamic_padding = true

[window.padding]
x = 2
y = 2
