[colors.bright]
black = "0x22212c"
blue = "0xaa99ff"
cyan = "0x99ffee"
green = "0xa2ff99"
magenta = "0xff99cc"
red = "0xffaa99"
white = "0xffffff"
yellow = "0xffff99"

[colors.cursor]
cursor = "0xf8f8f2"
text = "0x454158"

[colors.normal]
black = "0x22212c"
blue = "0x9580ff"
cyan = "0x80ffea"
green = "0x8aff80"
magenta = "0xff80bf"
red = "0xff9580"
white = "0xf8f8f2"
yellow = "0xffff80"

[colors.primary]
background = "0x22212c"
foreground = "0xf8f8f2"

[colors.selection]
background = "0x454158"
text = "0xf8f8f2"
