# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

# Lock displays to fixed workspaces
# https://nikitabobko.github.io/AeroSpace/guide.html#assign-workspaces-to-monitors
[workspace-to-monitor-force-assignment]
1 = ['lg ultrawide', 'built-in']
2 = ['studio display', 'lg hdr']
3 = ['built-in', 'lg ultrawide']

# Float CleanMyMac
[[on-window-detected]]
if.app-id = 'com.macpaw.CleanMyMac5'
run = ['layout floating']

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.main.binding]

# Switch mode to unlocked
# See: https://nikitabobko.github.io/AeroSpace/commands#mode
ctrl-a = 'mode unlocked'

ctrl-alt-h = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors left'
ctrl-alt-j = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors down'
ctrl-alt-k = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors up'
ctrl-alt-l = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors right'

ctrl-alt-d = 'layout floating tiling'
ctrl-alt-tab = 'focus-back-and-forth'

# 'unlocked' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.unlocked.binding]
ctrl-a = 'mode unlocked'
enter = 'mode main'
esc = 'mode main'

# Modes
w = 'mode window'
m = 'mode move'
r = 'mode resize'
g = 'mode group'
o = 'mode options'

# 'window' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.window.binding]
ctrl-a = 'mode unlocked'
enter = 'mode main'
esc = 'mode main'

# Modes
w = 'mode window'
m = 'mode move'
r = 'mode resize'
g = 'mode group'
o = 'mode options'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
h = 'focus --boundaries-action wrap-around-the-workspace left'
j = 'focus --boundaries-action wrap-around-the-workspace down'
k = 'focus --boundaries-action wrap-around-the-workspace up'
l = 'focus --boundaries-action wrap-around-the-workspace right'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
1 = 'workspace 1'
2 = 'workspace 2'
3 = 'workspace 3'
4 = 'workspace 4'
5 = 'workspace 5'
6 = 'workspace 6'
7 = 'workspace 7'
8 = 'workspace 8'
9 = 'workspace 9'

# See: https://nikitabobko.github.io/AeroSpace/commands#fullscreen
f = ['fullscreen', 'mode main']

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
d = ['layout floating tiling', 'mode main']

# 'move' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.move.binding]
ctrl-a = 'mode unlocked'
enter = 'mode main'
esc = 'mode main'

# Modes
w = 'mode window'
m = 'mode move'
r = 'mode resize'
g = 'mode group'
o = 'mode options'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
h = 'move left'
j = 'move down'
k = 'move up'
l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
1 = ['move-node-to-workspace 1', 'workspace 1']
2 = ['move-node-to-workspace 2', 'workspace 2']
3 = ['move-node-to-workspace 3', 'workspace 3']
4 = ['move-node-to-workspace 4', 'workspace 4']
5 = ['move-node-to-workspace 5', 'workspace 5']
6 = ['move-node-to-workspace 6', 'workspace 6']
7 = ['move-node-to-workspace 7', 'workspace 7']
8 = ['move-node-to-workspace 8', 'workspace 8']
9 = ['move-node-to-workspace 9', 'workspace 9']

# 'resize' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.resize.binding]
ctrl-a = 'mode unlocked'
enter = 'mode main'
esc = 'mode main'

# Modes
w = 'mode window'
m = 'mode move'
r = 'mode resize'
g = 'mode group'
o = 'mode options'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
minus = 'resize smart -50'
equal = 'resize smart +50'
h = 'resize width -50'
l = 'resize width +50'
j = 'resize height -50'
k = 'resize height +50'

# 'group' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.group.binding]
ctrl-a = 'mode unlocked'
enter = 'mode main'
esc = 'mode main'

# Modes
w = 'mode window'
m = 'mode move'
r = 'mode resize'
g = 'mode group'
o = 'mode options'

# See: https://nikitabobko.github.io/AeroSpace/commands#join-with
h = 'join-with left'
j = 'join-with down'
k = 'join-with up'
l = 'join-with right'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
s = 'layout accordion horizontal vertical'
t = 'layout tiles horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#flatten-workspace-tree
x = 'flatten-workspace-tree'

# 'options' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.options.binding]
ctrl-a = 'mode unlocked'
enter = 'mode main'
esc = 'mode main'

# Modes
w = 'mode window'
m = 'mode move'
r = 'mode resize'
g = 'mode group'
o = 'mode options'

# See: https://nikitabobko.github.io/AeroSpace/commands#reload-config
c = ['reload-config', 'mode main']
