#!/bin/sh

ln -nfs ~/bin/dotfiles/bash_profile ~/.bash_profile
ln -nfs ~/bin/dotfiles/bashrc ~/.bashrc
ln -nfs ~/bin/dotfiles/zshrc ~/.zshrc

ln -nfs ~/bin/dotfiles/npmrc ~/.npmrc
ln -nfs ~/bin/dotfiles/vim ~/.vim
ln -nfs ~/bin/dotfiles/vimrc ~/.vimrc
ln -nfs ~/bin/dotfiles/gvimrc ~/.gvimrc
ln -nfs ~/bin/dotfiles/gitconfig ~/.gitconfig
