#!/bin/sh

ln -nfs ~/bin/dotfiles/bash_profile ~/.bash_profile
ln -nfs ~/bin/dotfiles/bashrc ~/.bashrc
ln -nfs ~/bin/dotfiles/zshrc ~/.zshrc
ln -nfs ~/bin/dotfiles/tmux.conf ~/.tmux.conf
ln -nfs ~/bin/dotfiles/jslintrc ~/.jslintrc
ln -nfs ~/bin/dotfiles/gitignore_global ~/.gitignore_global
ln -nfs ~/bin/dotfiles/npmrc ~/.npmrc
ln -nfs ~/bin/dotfiles/vim ~/.vim
ln -nfs ~/bin/dotfiles/vimrc ~/.vimrc
ln -nfs ~/bin/dotfiles/gvimrc ~/.gvimrc
ln -nfs ~/bin/dotfiles/gitconfig ~/.gitconfig
ln -nfs ~/bin/dotfiles/ghci ~/.ghci
ln -nfs ~/bin/dotfiles/gitags /usr/local/bin/gitags
ln -nfs ~/bin/dotfiles/chcache /usr/local/bin/chcache
ln -nfs ~/bin/dotfiles/battery /usr/local/bin/battery
