#!/usr/bin/env sh

for bundle in vim/bundle/*; do
    echo "\nUPDATING $bundle"
    cd $bundle
    git reset --hard
    git clean -f
    git pull origin HEAD
    cd ../../..
done;

cd vim/bundle/command-t
git apply ../../dt_colorcol_linenum.patch
