""""""""""""""""""""""""""""""""""""""""
"
"  MacVim GUI configuration
"
se go-=r                  " no right scroll
se go-=L                  " no left scroll
se go-=T                  " no toolbar
se showtabline=1          " show tabs only if needed
" se fuopt=maxvert,maxhorz  " maximize
" se fu

function! DefFont()
    se guifont=ProFontX\ for\ PowerLine:h12
endfunction

function! BigFont()
    se guifont=Menlo:h18
endfunction

if has("gui_macvim")
    macmenu &File.New\ Tab key=<nop>
endif

call DefFont()
