. ~/.shell/env
. ~/.shell/config
. ~/.shell/aliases
. ~/.shell/zsh
. ~/.shell/functions
. /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
clear

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.iterm2_shell_integration.zsh ] && source ~/.iterm2_shell_integration.zsh

