#!/bin/sh

USER=$(whoami)
APACHE_USER=$(ps axho user,comm|grep -E "httpd|apache"|uniq|grep -v "root"|awk 'END {print $1}')

if [ -d app/cache ]
then
    sudo chmod +a "$USER allow delete,write,append,file_inherit,directory_inherit" app/cache app/logs
    sudo chmod +a "$APACHE_USER allow delete,write,append,file_inherit,directory_inherit" app/cache app/logs

    echo "app/cache & app/logs been properly chmod'ed for $USER and $APACHE_USER"
fi

if [ -d cache ]
then
    sudo chmod +a "$USER allow delete,write,append,file_inherit,directory_inherit" cache logs
    sudo chmod +a "$APACHE_USER allow delete,write,append,file_inherit,directory_inherit" cache logs

    echo "cache & logs been properly chmod'ed for $USER and $APACHE_USER"
fi
