#!/bin/sh
ctags -f TAGS \
    -h "\.php" -R \
    --exclude=\"\bin\" \
    --exclude=\"\app\" \
    --exclude=\"\web\" \
    --exclude=\"\.git\" \
    --totals=yes \
    --tag-relative=yes \
    --PHP-kinds=+cf \
    --regex-PHP='/abstract class ([^ ]*)/\1/c/' \
    --regex-PHP='/interface ([^ ]*)/\1/c/' \
    --regex-PHP='/(public |static |abstract |protected |private )+function ([^ (]*)/\2/f/'
