#!/usr/bin/env osascript
# Returns the current playing song in iTunes

if appIsRunning("iTunes") then
  tell application "iTunes"
    if exists name of current track then
      set current_track to the current track
      set track_name to the name of current_track
      set track_artist to the artist of current_track

      set now_playing to "♫  " & track_artist & " - " & track_name
      set trim_length to 40

      if length of now_playing is less than trim_length then
        set now_playing_trim to now_playing
      else
        set now_playing_trim to characters 1 thru trim_length of now_playing as string
      end if
    end if
  end tell
end if

on appIsRunning(appName)
  tell application "System Events" to (name of processes) contains appName
end appIsRunning
